### ISSUE TITLE
Write content for steps

### ISSUE THREAD

**Issue by vezwork** [esse-dev/borzoi#8]
- [ ] step 1 content is along the lines of 
     "Enable monetization on your site by adding the WM meta tag. Drag the meta tag to its place!"
     "Perfect! The monetization meta tag goes in the <head> of your website. 
     We’ll go over how to include your own monetization account at the end of the tutorial."

- [ ] step 2 content has to do with including Web Monetization JavaScript on your page to hide and show an element.
 
- [ ] step 3 content has to do with signing up with a wallet provider and continuing your Web Monetization creator journey.

**Comment by vezwork** [comment]
## Step 1 
### part 1
Get your site monetized by adding a Web Monetization meta tag. Try dragging the **meta tag** to its place in this example site's code.
* Developer note: hovering over **meta tag** could make the puzzle piece do a jumping animation.

### part 2 - After dragging the piece into place
Perfect! The Web Monetization meta tag goes in the `head` of your website.
You'll start receiving money as users who have started using Web Monetization spend time on your site.
We’ll go over how to include **your own monetization account** at the end of the tutorial.
* Developer note: could provide a link on **your own monetization account**, so interested users can jump to this info.

**Comment by sharon-wang** [comment]
**Step 1: Add monetization meta tag** -- 1 block
```
<meta name="monetization" content="$ilp.uphold.com/aEYQyH47UYPY">
```
**Step 2: Check for `document.monetization`** -- 1 block
```
if (document.monetization) {

} else {

}
```
**Step 3: Listen for `monetizationprogress` event** -- 1 block
```
document.monetization.addEventListener('monetizationprogress', event => {

});
```
**Step 4: Show/hide elements** -- 2 blocks

```
document.getElementById('ad').style.display = 'none'; // within monetization progress event
```
```
document.getElementById('ad').style.display = 'block'; // within else case for `document.monetization` check
```
**Congrats page with link to resources such as**
- https://github.com/esse-dev/web-monetization-base
- https://webmonetization.org/docs/getting-started
- https://webmonetization.org/#wallets
